name: coc-metals CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: coc-metals ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        node-version: [10, 12, 13]

    env:
      NODE_ENV: test

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: curl --compressed -o- -L https://yarnpkg.com/install.sh | bash

      - name: Checkout
        uses: actions/checkout@v1

      - name: Build Check
        run: yarn install

      - name: Style Check
        run: yarn format-check
