name: coc-metals CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: coc-metals ${{ matrix.os }} build
    runs-on: ${{ matrix.ox }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [10, 12, 13]
        
    env:
      NODE_ENV: test

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: action/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Yarn
        run: url --compressed -o- -L https://yarnpkg.com/install.sh | bash
      
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: yarn install
        run: yarn
      
      - name: yarn build
        run: yarn build
