name: coc-metals release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: "ubuntu-18.04"

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Yarn
        run: curl --compressed -o- -L https://yarnpkg.com/install.sh | bash

      - name: Setup git env
        run: |
          git config --global user.email "bot@scalameta.org"
          git config --global user.name "Scalameta bot"

      - name: Checkout
        uses: actions/checkout@v1

      - name: Get the tag version
        id: get_version
        run: echo ::set-output name=NEW_NEW_VERSION::${GITHUB_REF#refs/tags/v}

      - name: Install Dependencies
        run: yarn install

      - name: Set new version
        run: yarn version --no-git-tag-version --new-version ${{ steps.get_version.outputs.NEW_VERSION }}

      - name: Generate new changelog
        run: npx github-changes -o scalameta -r coc-metals --no-merges -t "coc-metals changelog" -k ${{ secrets.GITHUB_COC_METALS }}

      - name: Commit changes
        run: git commit -am "Release ${{ steps.get_version.outputs.NEW_VERSION }}"

      - name: Set npm auth
        run: echo "//registry.yarnpkg.com/:_authToken=${{ secrets.NPM_COC_METALS_PUBLISH }}" >>~/.npmrc

      - name: Publish
        run: yarn publish

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_COC_METALS }}
